services:
  - type: web
    name: api-canciones-crud
    env: docker
    repo: https://github.com/riofutabac/WebAvanzadasMicroservicios.git
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: canciones-db
          property: connectionString
    disks:
      - name: data
        mountPath: /var/data
        sizeGB: 1

databases:
  - name: canciones-db
    databaseName: canciones
    user: canciones_user